### PR TITLE
Pin minikube install to version 1.26.1

### LINKED ISSUE #350: Minikube version pinning
Pin minikube to:

```
$ minikube version
minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
```
Looks like minikube addons enable ingress is failing with minikube v1.27.0 because of a restrictive node selector on some of the pods created:
Node-Selectors:              kubernetes.io/os=linux
                             minikube.k8s.io/primary=true
This appears to be keeping it from working on macOS (i.e. darwin)

### PR DESCRIPTION
**Pull request by trmiller**
Fixes #350

### CODE REVIEW

**Review by bradbeck — APPROVED** [review]
Seems to work.

You will need to signoff on the commit to pass the DCO check.

File: platform/00-kubernetes-minikube-setup.sh [hunk 1]
```diff
@@ -55,7 +55,7 @@ echo -e "${C_GREEN}Installing packages if needed...${C_RESET_ALL}"
 case "${PLATFORM}" in
 
   Darwin)
-    minikube version || brew install minikube
+    minikube version || brew tap-new "$USER"/local-minikube; brew extract --version=1.26.1 minikube "$USER"/local-minikube; brew install minikube@1.26.1;
```
Comment (bradbeck) [inline platform/00-kubernetes-minikube-setup.sh:58]:
```suggestion
    minikube version || brew tap-new "$USER"/local-minikube; brew extract --version=1.26.1 minikube "$USER"/local-minikube; brew install minikube@1.26.1
```

**Review by pxp928 — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]
LGTM
